"""Synthetic terrestrial scan generator.

WHY THIS EXISTS
---------------
You cannot develop a cleanup algorithm on a 5 GB file, and you cannot measure
one without ground truth. This module gives both: a plaza scanned from several
tripod positions, generated by *actually casting rays* against analytic
geometry so that occlusion is physically correct.

That last part matters more than it sounds. If you fake a scan by sampling
surfaces and then randomly hiding some points, stations will appear to see
through walls, the carving will look brilliant, and none of it will transfer
to real data. Here, a pedestrian standing in front of a facade genuinely
shadows that facade in that station and only that station. Which is exactly
the condition that makes ghost removal possible, and exactly what breaks when
the geometry is faked.

The scene deliberately includes cases the method CANNOT solve, so the metrics
are not flattering:
  * a person who stands still across two stations, and therefore defends
    themselves from deletion
  * pedestrians pressed against facades, where the free-space margin is
    fighting the wall
  * mixed-pixel noise at depth discontinuities
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np

from ..types import Scene, Station

INF = np.inf


# --------------------------------------------------------------------------
# primitives
# --------------------------------------------------------------------------


@dataclass
class Primitive:
    dynamic: bool = False

    def intersect(self, o: np.ndarray, d: np.ndarray) -> np.ndarray:
        raise NotImplementedError


@dataclass
class AxisPlane(Primitive):
    """Axis-aligned bounded plane. `axis` 0=x, 1=y, 2=z; plane at `value`."""

    axis: int = 2
    value: float = 0.0
    bounds: tuple = ((-1, 1), (-1, 1))  # bounds on the other two axes, in order
    dynamic: bool = False

    def intersect(self, o, d):
        a = self.axis
        with np.errstate(divide="ignore", invalid="ignore"):
            t = (self.value - o[a]) / d[:, a]
        t = np.where(np.isfinite(t) & (t > 1e-6), t, INF)
        others = [i for i in range(3) if i != a]
        with np.errstate(invalid="ignore"):
            p = o + d * t[:, None]
        ok = np.ones(len(d), dtype=bool)
        for k, i in enumerate(others):
            lo, hi = self.bounds[k]
            ok &= (p[:, i] >= lo) & (p[:, i] <= hi)
        return np.where(ok, t, INF)


@dataclass
class VCylinder(Primitive):
    """Vertical cylinder, infinite-wall side only (no caps needed here)."""

    cx: float = 0.0
    cy: float = 0.0
    r: float = 1.0
    z0: float = 0.0
    z1: float = 1.0
    dynamic: bool = False

    def intersect(self, o, d):
        ox, oy = o[0] - self.cx, o[1] - self.cy
        dx, dy = d[:, 0], d[:, 1]
        a = dx * dx + dy * dy
        b = 2.0 * (ox * dx + oy * dy)
        c = ox * ox + oy * oy - self.r * self.r
        disc = b * b - 4 * a * c
        out = np.full(len(d), INF)
        m = (disc > 0) & (a > 1e-12)
        if not m.any():
            return out
        sq = np.sqrt(disc[m])
        t1 = (-b[m] - sq) / (2 * a[m])
        t2 = (-b[m] + sq) / (2 * a[m])
        for t in (t1, t2):
            z = o[2] + d[m, 2] * t
            good = (t > 1e-6) & (z >= self.z0) & (z <= self.z1)
            cur = out[m]
            cand = np.where(good, t, INF)
            out[m] = np.minimum(cur, cand)
        return out


@dataclass
class Box(Primitive):
    lo: tuple = (0, 0, 0)
    hi: tuple = (1, 1, 1)
    dynamic: bool = False

    def intersect(self, o, d):
        lo = np.asarray(self.lo, dtype=np.float64)
        hi = np.asarray(self.hi, dtype=np.float64)
        with np.errstate(divide="ignore", invalid="ignore"):
            t0 = (lo - o) / d
            t1 = (hi - o) / d
        tmin = np.maximum.reduce(np.minimum(t0, t1), axis=1)
        tmax = np.minimum.reduce(np.maximum(t0, t1), axis=1)
        hit = (tmax >= np.maximum(tmin, 1e-6)) & np.isfinite(tmin)
        return np.where(hit, tmin, INF)


# --------------------------------------------------------------------------
# scanner simulation
# --------------------------------------------------------------------------


def _directions(az_steps: int, el_steps: int, el_min: float, el_max: float):
    az = np.linspace(-np.pi, np.pi, az_steps, endpoint=False)
    el = np.linspace(el_min, el_max, el_steps)
    A, E = np.meshgrid(az, el, indexing="ij")
    A = A.ravel()
    E = E.ravel()
    ce = np.cos(E)
    return np.stack([ce * np.cos(A), ce * np.sin(A), np.sin(E)], axis=1)


def scan(
    origin: np.ndarray,
    primitives: list[Primitive],
    az_steps: int = 2000,
    el_steps: int = 380,
    el_min_deg: float = -38.0,
    el_max_deg: float = 55.0,
    max_range: float = 90.0,
    range_noise_base: float = 0.003,
    range_noise_per_m: float = 0.00025,
    mixed_pixel_frac: float = 0.003,
    rng: np.random.Generator | None = None,
    dir_chunk: int = 200_000,
):
    """Cast a scanner's worth of rays and return (points, label).

    Label convention, three classes rather than two:
        0 = static surface
        1 = dynamic (a moving object was there during this scan)
        2 = mixed-pixel noise (the beam straddled a depth edge)

    The third class exists because of a real measurement problem found on the
    first run of this generator. With only static/dynamic labels, every noise
    point the pipeline correctly removed was scored as destroyed geometry, and
    the reported surface damage rate came out at 0.27% when the true damage
    was near zero. A two-class ground truth on this task does not measure what
    it claims to measure.
    """
    rng = rng or np.random.default_rng(0)
    o = np.asarray(origin, dtype=np.float64).reshape(3)
    D = _directions(az_steps, el_steps, np.radians(el_min_deg), np.radians(el_max_deg))

    pts_out, dyn_out = [], []
    for lo in range(0, len(D), dir_chunk):
        d = D[lo : lo + dir_chunk]
        best_t = np.full(len(d), INF)
        best_dyn = np.zeros(len(d), dtype=bool)
        for prim in primitives:
            t = prim.intersect(o, d)
            closer = t < best_t
            best_t = np.where(closer, t, best_t)
            if prim.dynamic:
                best_dyn = np.where(closer, True, best_dyn)
            else:
                best_dyn = np.where(closer, False, best_dyn)

        hit = np.isfinite(best_t) & (best_t <= max_range)
        if not hit.any():
            continue
        t = best_t[hit]
        dd = d[hit]
        dyn = best_dyn[hit]

        # range noise, applied along the beam as a real scanner would
        sigma = range_noise_base + range_noise_per_m * t
        t = t + rng.normal(0.0, 1.0, size=len(t)) * sigma

        # mixed pixels: a fraction of beams straddle a depth discontinuity and
        # report a blended range somewhere between near and far surface
        n_mix = int(mixed_pixel_frac * len(t))
        idx = np.zeros(0, dtype=np.int64)
        if n_mix > 0:
            idx = rng.choice(len(t), size=n_mix, replace=False)
            t[idx] = t[idx] * rng.uniform(0.35, 0.95, size=n_mix)

        lab = dyn.astype(np.int8)  # 0 static, 1 dynamic
        if n_mix > 0:
            lab[idx] = 2  # mixed pixel, regardless of what it originally hit

        pts_out.append(o + dd * t[:, None])
        dyn_out.append(lab)

    if not pts_out:
        return np.zeros((0, 3)), np.zeros(0, dtype=np.int8)
    return np.concatenate(pts_out), np.concatenate(dyn_out)


# --------------------------------------------------------------------------
# the plaza
# --------------------------------------------------------------------------


def _static_geometry() -> list[Primitive]:
    X, Y = 30.0, 20.0
    prims: list[Primitive] = [
        # ground
        AxisPlane(axis=2, value=0.0, bounds=((-X, X), (-Y, Y))),
        # four facades
        AxisPlane(axis=1, value=Y, bounds=((-X, X), (0.0, 12.0))),
        AxisPlane(axis=1, value=-Y, bounds=((-X, X), (0.0, 10.0))),
        AxisPlane(axis=0, value=X, bounds=((-Y, Y), (0.0, 14.0))),
        AxisPlane(axis=0, value=-X, bounds=((-Y, Y), (0.0, 11.0))),
        # fountain basin and central obelisk
        VCylinder(cx=0.0, cy=0.0, r=3.0, z0=0.0, z1=1.15),
        VCylinder(cx=0.0, cy=0.0, r=0.45, z0=0.0, z1=4.2),
        # a free-standing column
        VCylinder(cx=10.0, cy=5.0, r=0.62, z0=0.0, z1=8.0),
        # two kiosks
        Box(lo=(-20.0, 8.0, 0.0), hi=(-14.0, 12.0, 3.4)),
        Box(lo=(16.0, -14.0, 0.0), hi=(22.0, -9.0, 3.0)),
        # benches
        Box(lo=(-6.0, -12.0, 0.0), hi=(-1.0, -11.4, 0.48)),
        Box(lo=(4.0, -12.0, 0.0), hi=(9.0, -11.4, 0.48)),
        Box(lo=(-6.0, 13.0, 0.0), hi=(-1.0, 13.6, 0.48)),
    ]
    return prims


def _person(x: float, y: float, rng) -> list[Primitive]:
    """A crude standing figure: body cylinder plus a head. Good enough: the
    algorithm never sees a shape, only occupancy."""
    h = rng.uniform(1.62, 1.86)
    return [
        VCylinder(cx=x, cy=y, r=rng.uniform(0.20, 0.28), z0=0.0, z1=h - 0.22, dynamic=True),
        VCylinder(cx=x, cy=y, r=0.11, z0=h - 0.22, z1=h, dynamic=True),
    ]


def build_plaza_scene(
    seed: int = 7,
    az_steps: int = 1800,
    el_steps: int = 340,
    n_walkers: int = 11,
    n_loiterers: int = 2,
) -> Scene:
    """A four-station plaza capture with pedestrians.

    `n_loiterers` people stand in the SAME place across two stations. Those
    are deliberately unremovable by cross-station carving, and they should
    show up in the miss column of the metrics. If they do not, the metrics
    are lying.
    """
    rng = np.random.default_rng(seed)
    static = _static_geometry()

    origins = [
        np.array([-12.0, -8.0, 1.62]),
        np.array([14.0, -6.0, 1.60]),
        np.array([8.0, 10.0, 1.64]),
        np.array([-6.0, 12.0, 1.58]),
    ]

    # loiterers: fixed positions, present in stations 0 and 1 only
    loiterers = [(rng.uniform(-18, 18), rng.uniform(-12, 12)) for _ in range(n_loiterers)]

    stations = []
    for i, o in enumerate(origins):
        people: list[Primitive] = []

        # walkers: fresh positions every station, this is what makes ghosts
        for _ in range(n_walkers):
            if rng.random() < 0.35:
                # pressed up against a facade: the hard case
                side = rng.integers(0, 4)
                if side == 0:
                    x, y = rng.uniform(-28, 28), 20.0 - rng.uniform(0.45, 1.1)
                elif side == 1:
                    x, y = rng.uniform(-28, 28), -20.0 + rng.uniform(0.45, 1.1)
                elif side == 2:
                    x, y = 30.0 - rng.uniform(0.45, 1.1), rng.uniform(-18, 18)
                else:
                    x, y = -30.0 + rng.uniform(0.45, 1.1), rng.uniform(-18, 18)
            else:
                x, y = rng.uniform(-27, 27), rng.uniform(-18, 18)
            people += _person(x, y, rng)

        if i in (0, 1):
            for (x, y) in loiterers:
                people += _person(x, y, rng)

        pts, lab = scan(
            o,
            static + people,
            az_steps=az_steps,
            el_steps=el_steps,
            rng=np.random.default_rng(seed * 100 + i),
        )
        stations.append(
            Station(
                name=f"ScanPos{i+1:03d}",
                points=pts,
                origin=o,
                labels=lab,
                meta={"synthetic": True, "n_people": n_walkers + (n_loiterers if i in (0, 1) else 0)},
            )
        )

    return Scene(
        name="synthetic_plaza",
        stations=stations,
        meta={
            "source": "scan2twin.io.synthetic",
            "seed": seed,
            "note": (
                "Generated by ray casting against analytic geometry. Occlusion "
                "is physically correct. Ground truth is exact by construction, "
                "which makes it BETTER than any real benchmark and therefore "
                "not a substitute for one."
            ),
        },
    )


def estimate_angular_resolution(station: Station) -> float:
    """Estimate a station's angular sampling in degrees, from the data alone.

    Real scan files often do not tell you the resolution they were shot at,
    and the range image is worthless if its bins are far off it. This is the
    fallback: assume a roughly regular angular grid and invert the point count.
    """
    d = station.points - station.origin
    r = np.maximum(np.linalg.norm(d, axis=1), 1e-9)
    el = np.arcsin(np.clip(d[:, 2] / r, -1, 1))
    el_span = float(el.max() - el.min())
    n = len(station)
    if n < 100 or el_span <= 0:
        return 0.1
    res_rad = np.sqrt(2 * np.pi * el_span / n)
    return float(np.degrees(res_rad))
